name: gen
description: "A new Flutter package project."
version: 0.0.1
homepage:

environment:
  sdk: ^3.8.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  json_annotation: ^4.9.0
  flutter_svg: ^2.2.0
  lottie: ^3.3.1
  equatable: ^2.0.7
  envied: ^1.1.1
  flutter_gen: ^5.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  very_good_analysis: ^9.0.0
  envied_generator: ^1.1.1
  json_serializable: ^6.2.0
  build_runner: ^2.4.6
  flutter_gen_runner: ^5.10.0

flutter_gen:
  output: lib/src/asset/
  integrations:
    lottie: true
    flutter_svg: true

  colors:
    inputs:
      - assets/color/colors.xml

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # To add assets to your package, add an assets section, like this:
  assets:
    - assets/color/
    - assets/lottie/
    - assets/icons/
    - assets/images/
