// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmN3lFBNia4HMfcHPBp-b_8qlqt4G3yBg',
    appId: '1:44501532854:web:8af0c8320152b0b974a617',
    messagingSenderId: '44501532854',
    projectId: 'shartfli',
    authDomain: 'shartfli.firebaseapp.com',
    storageBucket: 'shartfli.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1flxHYbTVIrAtQjLgOU5xI_TBvBeyaZw',
    appId: '1:44501532854:android:648f67e58769f50374a617',
    messagingSenderId: '44501532854',
    projectId: 'shartfli',
    storageBucket: 'shartfli.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMHAALCpB1XRGAkC5or8w6PWAwL7PeXKs',
    appId: '1:44501532854:ios:ac4bc757cd24e19674a617',
    messagingSenderId: '44501532854',
    projectId: 'shartfli',
    storageBucket: 'shartfli.firebasestorage.app',
    iosBundleId: 'com.example.architecture',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAMHAALCpB1XRGAkC5or8w6PWAwL7PeXKs',
    appId: '1:44501532854:ios:ac4bc757cd24e19674a617',
    messagingSenderId: '44501532854',
    projectId: 'shartfli',
    storageBucket: 'shartfli.firebasestorage.app',
    iosBundleId: 'com.example.architecture',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDmN3lFBNia4HMfcHPBp-b_8qlqt4G3yBg',
    appId: '1:44501532854:web:822f6d5c2d256fdd74a617',
    messagingSenderId: '44501532854',
    projectId: 'shartfli',
    authDomain: 'shartfli.firebaseapp.com',
    storageBucket: 'shartfli.firebasestorage.app',
  );
}
